@host = https://localhost:7159
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJUYXNrTWFuYWdlciIsImlzcyI6IlRhc2tNYW5hZ2VyIiwiZXhwIjoxNzkxMjE5NTM4LCJzdWIiOiIyIiwiZW1haWwiOiJhbGUyMjJ4QGV4YW1wbGUuY29tIiwiaWF0IjoxNzkxMjE1OTM4LCJuYmYiOjE3OTEyMTU5Mzh9.bHB3hCw7_EXtNPvmY1CCfwxPrVUuHi3-fykOqzM9nmc

### 1. Регистрация
POST {{host}}/auth/register
Content-Type: application/json

{
  "email": "ale222x@example.com",
  "password": "12345678",
  "name": "BOB"
}

### 2. Вход
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "ale222x@example.com",
  "password": "12345678"
}

### 3. Кто я (нужен токен)
GET {{host}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJUYXNrTWFuYWdlciIsImlzcyI6IlRhc2tNYW5hZ2VyIiwiZXhwIjoxNzkxMTE4NTUwLCJzdWIiOiIxIiwiZW1haWwiOiJhbGV4QGV4YW1wbGUuY29tIiwiaWF0IjoxNzkxMTE0OTUwLCJuYmYiOjE3OTExMTQ5NTB9.-nR5YoKXsvL3QBNuddIv74It60tPrVOz7cABoHGDHCk

### 4. Создать проект
POST {{host}}/projects
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Мой первый проект",
  "description": "Учебный проект для API"
}

### 5. Список моих проектов
GET {{host}}/projects
Authorization: Bearer {{token}}

### 6. Один проект
GET {{host}}/projects/1
Authorization: Bearer {{token}}

### 7. Изменить проект
PATCH {{host}}/projects/7
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Новое имя1111"
}

### 8. Удалить проект
DELETE {{host}}/projects/7
Authorization: Bearer {{token}}