@host = https://localhost:7159
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJUYXNrTWFuYWdlciIsImlzcyI6IlRhc2tNYW5hZ2VyIiwiZXhwIjoxNzkxNDc2MjY1LCJzdWIiOiIxIiwiZW1haWwiOiJhbGV4QGV4YW1wbGUuY29tIiwiaWF0IjoxNzkxNDcyNjY1LCJuYmYiOjE3OTE0NzI2NjV9.eZU5yigeAT26oxzghsJIzaVuB3b52Bb1-2Kd9gKHkbU
@tokenBob = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJUYXNrTWFuYWdlciIsImlzcyI6IlRhc2tNYW5hZ2VyIiwiZXhwIjoxNzkxNDc2MjI4LCJzdWIiOiIyIiwiZW1haWwiOiJhbGUyMjJ4QGV4YW1wbGUuY29tIiwiaWF0IjoxNzkxNDcyNjI4LCJuYmYiOjE3OTE0NzI2Mjh9.bFaJIFhzJkj12RWVQfDx5hRyR8a5AnS6NgXgrv8Jp-Y

### 1. Регистрация
POST {{host}}/auth/register
Content-Type: application/json

{
  "email": "ale222x@example.com",
  "password": "12345678",
  "name": "BOB"
}

### 2. Вход
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "alex@example.com",
  "password": "12345678"
}

### 3. Кто я (нужен токен)
GET {{host}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJUYXNrTWFuYWdlciIsImlzcyI6IlRhc2tNYW5hZ2VyIiwiZXhwIjoxNzkxMTE4NTUwLCJzdWIiOiIxIiwiZW1haWwiOiJhbGV4QGV4YW1wbGUuY29tIiwiaWF0IjoxNzkxMTE0OTUwLCJuYmYiOjE3OTExMTQ5NTB9.-nR5YoKXsvL3QBNuddIv74It60tPrVOz7cABoHGDHCk

### 4. Создать проект
POST {{host}}/projects
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Мой первый проект",
  "description": "Учебный проект для API"
}

### 5. Список моих проектов
GET {{host}}/projects
Authorization: Bearer {{tokenBob}}

### 6. Один проект
GET {{host}}/projects/2
Authorization: Bearer {{tokenBob}}

### 7. Изменить проект
PATCH {{host}}/projects/2
Content-Type: application/json
Authorization: Bearer {{tokenBob}}

{
  "name": "Новое имя1111"
}

### 8. Удалить проект
DELETE {{host}}/projects/2
Authorization: Bearer {{tokenBob}}



### 9. Список участников
GET {{host}}/projects/2/members
Authorization: Bearer {{tokenBob}}

### 10. Пригласить Боба
POST {{host}}/projects/2/members
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "ale222x@example.com"
}

### 11. Боб приглашает кого-то (должен получить 403)
POST {{host}}/projects/2/members
Content-Type: application/json
Authorization: Bearer {{tokenBob}}

{
  "email": "alex@example.com"
}

### 12. Боб покидает проект
DELETE {{host}}/projects/2/members/2
Authorization: Bearer {{token}}